baseurl: /
timezone: Asia/Shanghai
encoding: utf-8
markdown: kramdown

blogName: Sincerajn's blog
moreKeyWords: sincerajn 博客 linux python html css javascript github Jekyll 教程 日志 besiege rimwrold